// <auto-generated />
namespace MyshopWebDataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TryTodelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TryTodelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201907181713411_TryTodelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
